name: Eatery Dev Server - CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup application properties file for test
        run: echo "${{ secrets.APPLICATION_PROPERTIES_TEST }}" > ./src/main/resources/application-test.properties

      - name: Setup environment variables
        run: echo "${{ secrets.ENV_PROPERTIES_DEV }}" > ./src/main/resources/env.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Upload Jacoco Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Docker build and push
        if: ${{ !failure() }}
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DEV_DOCKER_REPO }} -f Dockerfile-dev .
          docker push ${{ secrets.DEV_DOCKER_REPO }}

      - name: Executing remote ssh commands with docker compose for Continuous Delivery
        if: ${{ !failure() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_AWS_EC2_HOST }}
          username: ${{ secrets.DEV_AWS_EC2_USERNAME }}
          key: ${{ secrets.DEV_AWS_EC2_KEY }}
          script: |
            cd /home/ec2-user/fmr
            docker-compose down
            docker pull ${{ secrets.DEV_DOCKER_REPO }}
            docker-compose up -d
